#!/usr/bin/env python3
"""
Build examples/reeval/ABLATION_TABLE.md from reeval/*/result.txt files.

Includes:
  - Clean ablation matrix (names starting with ablation- or known clean val runs)
  - Other reeval runs for reference (protocol may differ)
"""
from __future__ import annotations

import re
from pathlib import Path

EXAMPLES = Path(__file__).resolve().parent
REEVAL = EXAMPLES / "reeval"
OUT = REEVAL / "ABLATION_TABLE.md"

# Preferred order for the clean matrix
CLEAN_ORDER = [
    "ablation-linear-val",
    "ablation-physio-val",
    "ablation-physio-residual-val",
    "ablation-physio-residual-intensity-val",
    "run-huber-128-delta12-intensity-val",  # same recipe; existing best
    "ablation-adafs-intensity-val",
    "ablation-personal-val",
    "run-huber-128-delta12-personal-val",
    "ablation-p2-physio-val",
    "run-huber-128-delta12-intensity-p2-val",
    "ablation-meanbias-val",
    "run-huber-128-delta12-intensity-meanbias05-val",
]


def parse_result(path: Path) -> dict:
    text = path.read_text()
    d: dict = {"path": str(path), "name": path.parent.name}
    for line in text.splitlines():
        if "=" not in line:
            # first line may be bare name
            if line.strip() and "name" not in d:
                d.setdefault("title", line.strip())
            continue
        # tokenized key=value on long lines
        for token in line.split():
            if "=" not in token:
                continue
            k, v = token.split("=", 1)
            d[k] = v
        # also full-line key=value
        if line.count("=") == 1 and " " not in line.split("=", 1)[0]:
            k, v = line.split("=", 1)
            d[k] = v
    # normalize floats
    for key in list(d):
        if key in ("path", "name", "title"):
            continue
        try:
            if re.fullmatch(r"-?\d+", d[key]):
                d[key] = int(d[key])
            else:
                d[key] = float(d[key])
        except (ValueError, TypeError):
            pass
    return d


def fmt(v, digits=2):
    if v is None or v == "":
        return "—"
    if isinstance(v, float):
        return f"{v:.{digits}f}"
    return str(v)


def row_from(d: dict) -> dict:
    return {
        "name": d.get("name", ""),
        "val_fraction": d.get("val_fraction"),
        "physio": d.get("physiological"),
        "residual": d.get("residual"),
        "adafs": d.get("adafs"),
        "feature_set": d.get("feature_set"),
        "mean_bias": d.get("mean_bias_weight", 0),
        "p2": d.get("physio_subject_stable") or d.get("intensity_embedding"),
        "horizon_mae": d.get("MAE"),
        "val_mae": d.get("val_MAE"),
        "full_mean": d.get("full_mean_workout_MAE"),
        "full_median": d.get("full_median_workout_MAE"),
        "full_pooled": d.get("full_pooled_MAE"),
        "full_rmse": d.get("full_pooled_RMSE"),
    }


def is_clean_val(d: dict) -> bool:
    """Clean protocol: has val_fraction and full-workout metrics."""
    return d.get("val_fraction") is not None and d.get("full_mean_workout_MAE") is not None


def main():
    results = []
    for path in sorted(REEVAL.glob("*/result.txt")):
        results.append(parse_result(path))

    by_name = {r["name"]: r for r in results}
    clean = [r for r in results if is_clean_val(r)]
    other = [r for r in results if not is_clean_val(r)]

    # Ordered clean rows: prefer CLEAN_ORDER, then any other clean
    ordered_clean = []
    seen = set()
    for name in CLEAN_ORDER:
        if name in by_name and is_clean_val(by_name[name]):
            ordered_clean.append(by_name[name])
            seen.add(name)
    for r in sorted(clean, key=lambda x: x["name"]):
        if r["name"] not in seen:
            ordered_clean.append(r)

    lines = []
    lines.append("# Clean ablation / reevaluation table")
    lines.append("")
    lines.append("Generated by `examples/summarize_ablations.py`.")
    lines.append("")
    lines.append("## Protocol (clean rows)")
    lines.append("")
    lines.append("- Sport: **run**")
    lines.append("- History: **all-prior** (chronological)")
    lines.append("- Checkpointing: **validation only** (`val_fraction` from `in_train`)")
    lines.append("- Held-out: `~in_train` run workouts only for final metrics")
    lines.append("- Primary metric: **stitched full-workout mean MAE (BPM)**")
    lines.append("- Default training recipe: seq=128, stride=64, Huber δ=12, wd=1e-4")
    lines.append("")
    lines.append("## Paper vs clean baseline")
    lines.append("")
    lines.append("| Source | Metric | Value | Notes |")
    lines.append("|--------|--------|------:|-------|")
    lines.append("| Published paper | MAE | 5.2 | Original notebook procedure; not clean held-out full-workout |")
    lines.append("| Published paper | RMSE | 8.1 | Same |")
    best = by_name.get("run-huber-128-delta12-intensity-val") or by_name.get(
        "ablation-physio-residual-intensity-val"
    )
    if best and is_clean_val(best):
        lines.append(
            f"| **Best clean open-loop** (`{best['name']}`) | mean workout MAE | "
            f"**{fmt(best.get('full_mean_workout_MAE'), 2)}** | val-selected, full-workout |"
        )
        lines.append(
            f"| | median workout MAE | {fmt(best.get('full_median_workout_MAE'), 2)} | |"
        )
        lines.append(
            f"| | pooled MAE / RMSE | {fmt(best.get('full_pooled_MAE'), 2)} / "
            f"{fmt(best.get('full_pooled_RMSE'), 2)} | |"
        )
    lines.append("")
    lines.append("## Clean-protocol runs (comparable)")
    lines.append("")
    lines.append(
        "| Run | Physio | Residual | AdaFS | Features | "
        "Full mean MAE | Full median | Pooled MAE | Val MAE | Horizon MAE |"
    )
    lines.append(
        "|-----|:------:|:--------:|:-----:|----------|"
        "--------------:|------------:|-----------:|--------:|------------:|"
    )
    for r in ordered_clean:
        row = row_from(r)
        lines.append(
            f"| `{row['name']}` | {row['physio']} | {row['residual']} | {row['adafs']} | "
            f"{row['feature_set'] or '—'} | "
            f"**{fmt(row['full_mean'], 2)}** | {fmt(row['full_median'], 2)} | "
            f"{fmt(row['full_pooled'], 2)} | {fmt(row['val_mae'], 2)} | {fmt(row['horizon_mae'], 2)} |"
        )
    if not ordered_clean:
        lines.append("| *(no clean full-workout val runs yet — run `run_clean_ablations.py`)* | | | | | | | | | |")

    lines.append("")
    lines.append("## Interpretation notes")
    lines.append("")
    lines.append(
        "- Prefer **Full mean MAE** for open-loop comparison; horizon MAE is first "
        f"`seq_length` steps only."
    )
    lines.append(
        "- Runs without `val_fraction` in `result.txt` may have selected checkpoints "
        "on the held-out loader (older protocol) and are listed below for reference only."
    )
    lines.append(
        "- Paper Table 4 (without AdaFS / without personalized parameters) is **not** "
        "reproduced: those components were inactive in the original trained forward path."
    )
    lines.append("")
    lines.append("## Other reeval runs (reference; protocol may differ)")
    lines.append("")
    lines.append("| Run | Full mean MAE | Horizon MAE | Notes |")
    lines.append("|-----|--------------:|------------:|-------|")
    for r in sorted(other, key=lambda x: x["name"]):
        notes = []
        if r.get("val_fraction") is None:
            notes.append("no val_fraction field")
        if r.get("full_mean_workout_MAE") is None:
            notes.append("no full-workout")
        lines.append(
            f"| `{r['name']}` | {fmt(r.get('full_mean_workout_MAE'), 2)} | "
            f"{fmt(r.get('MAE'), 2)} | {'; '.join(notes) or '—'} |"
        )

    lines.append("")
    lines.append("## How to refresh")
    lines.append("")
    lines.append("```bash")
    lines.append("cd examples")
    lines.append("python3 run_clean_ablations.py --skip-existing")
    lines.append("python3 summarize_ablations.py")
    lines.append("```")
    lines.append("")

    OUT.write_text("\n".join(lines) + "\n")
    print(f"Wrote {OUT}")
    print(f"Clean comparable runs: {len(ordered_clean)}")
    print(f"Other runs: {len(other)}")


if __name__ == "__main__":
    main()
